In [1]:
import pandas as pd

In [8]:
import pandas as pd
import csv

path = 'data/candidate-list-of-svhc-for-authorisation-export.csv'

df = pd.read_csv(
    path,
    sep='\t',
    quoting=csv.QUOTE_NONE,   # don't let pandas interpret " at all
    encoding='utf-8-sig',     # handles the BOM if present
    index_col=False           # ignore the trailing empty column from the trailing tab
)

In [6]:
df.head()

  "Substance name"\t"Description"\t"EC No."\t"CAS No."\t"Reason for inclusion"\t"Date of inclusion"\t"Decision"\t"IUCLID dataset"\t"Support document"\t"Response to comments"\t"Remarks"
0  "n-hexane"\t""\t"203-777-6"\t"110-54-3"\t"Spec...
1  "4,4'-[2,2,2-trifluoro-1-(trifluoromethyl)ethy...
2  "Benzyltriphenylphosphonium, salt with 4,4'-[2...
3  "disodium 4,4'-[2,2,2-trifluoro-1-(trifluorome...
4  "N,N-dibutyl-N-methylbutan-1-aminium 4-[1,1,1,...

In [9]:
# Strip leading/trailing quote characters from every string column
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.strip('"')

df.head()

,"""Substance name""","""Description""","""EC No.""","""CAS No.""","""Reason for inclusion""","""Date of inclusion""","""Decision""","""IUCLID dataset""","""Support document""","""Response to comments""","""Remarks""",Unnamed: 11
0,n-hexane,,203-777-6,110-54-3,Specific target organ toxicity after repeated ...,04-Feb-2026,https://echa.europa.eu/documents/10162/2b029c1...,,https://echa.europa.eu/documents/10162/fee1469...,https://echa.europa.eu/documents/10162/9c49de6...,N-hexane is identified as a substance of very ...,NaN
1,"4,4'-[2,2,2-trifluoro-1-(trifluoromethyl)ethyl...",,-,-,Toxic for reproduction (Article 57c),04-Feb-2026,https://echa.europa.eu/documents/10162/71f21fe...,,https://echa.europa.eu/documents/10162/e04eb45...,https://echa.europa.eu/documents/10162/64c4fd7...,,NaN
2,"Benzyltriphenylphosphonium, salt with 4,4'-[2,...",,278-305-5,75768-65-9,Toxic for reproduction (Article 57c),04-Feb-2026,https://echa.europa.eu/documents/10162/71f21fe...,,https://echa.europa.eu/documents/10162/e04eb45...,https://echa.europa.eu/documents/10162/64c4fd7...,,NaN
3,"disodium 4,4'-[2,2,2-trifluoro-1-(trifluoromet...",,425-060-9,-,Toxic for reproduction (Article 57c),04-Feb-2026,https://echa.europa.eu/documents/10162/71f21fe...,,https://echa.europa.eu/documents/10162/e04eb45...,https://echa.europa.eu/documents/10162/64c4fd7...,,NaN
4,"N,N-dibutyl-N-methylbutan-1-aminium 4-[1,1,1,3...",,443-330-4,-,Toxic for reproduction (Article 57c),04-Feb-2026,https://echa.europa.eu/documents/10162/71f21fe...,,https://echa.europa.eu/documents/10162/e04eb45...,https://echa.europa.eu/documents/10162/64c4fd7...,,NaN

In [10]:
df.columns

Index(['"Substance name"', '"Description"', '"EC No."', '"CAS No."',
       '"Reason for inclusion"', '"Date of inclusion"', '"Decision"',
       '"IUCLID dataset"', '"Support document"', '"Response to comments"',
       '"Remarks"', 'Unnamed: 11'],
      dtype='object')

In [15]:
df.columns = df.columns.str.strip('"')  # Strip whitespace from column names

In [16]:
df.columns

Index(['Substance name', 'Description', 'EC No.', 'CAS No.',
       'Reason for inclusion', 'Date of inclusion', 'Decision',
       'IUCLID dataset', 'Support document', 'Response to comments', 'Remarks',
       'Unnamed: 11'],
      dtype='object')

In [17]:
df.head()

,Substance name,Description,EC No.,CAS No.,Reason for inclusion,Date of inclusion,Decision,IUCLID dataset,Support document,Response to comments,Remarks,Unnamed: 11
0,n-hexane,,203-777-6,110-54-3,Specific target organ toxicity after repeated ...,04-Feb-2026,https://echa.europa.eu/documents/10162/2b029c1...,,https://echa.europa.eu/documents/10162/fee1469...,https://echa.europa.eu/documents/10162/9c49de6...,N-hexane is identified as a substance of very ...,NaN
1,"4,4'-[2,2,2-trifluoro-1-(trifluoromethyl)ethyl...",,-,-,Toxic for reproduction (Article 57c),04-Feb-2026,https://echa.europa.eu/documents/10162/71f21fe...,,https://echa.europa.eu/documents/10162/e04eb45...,https://echa.europa.eu/documents/10162/64c4fd7...,,NaN
2,"Benzyltriphenylphosphonium, salt with 4,4'-[2,...",,278-305-5,75768-65-9,Toxic for reproduction (Article 57c),04-Feb-2026,https://echa.europa.eu/documents/10162/71f21fe...,,https://echa.europa.eu/documents/10162/e04eb45...,https://echa.europa.eu/documents/10162/64c4fd7...,,NaN
3,"disodium 4,4'-[2,2,2-trifluoro-1-(trifluoromet...",,425-060-9,-,Toxic for reproduction (Article 57c),04-Feb-2026,https://echa.europa.eu/documents/10162/71f21fe...,,https://echa.europa.eu/documents/10162/e04eb45...,https://echa.europa.eu/documents/10162/64c4fd7...,,NaN
4,"N,N-dibutyl-N-methylbutan-1-aminium 4-[1,1,1,3...",,443-330-4,-,Toxic for reproduction (Article 57c),04-Feb-2026,https://echa.europa.eu/documents/10162/71f21fe...,,https://echa.europa.eu/documents/10162/e04eb45...,https://echa.europa.eu/documents/10162/64c4fd7...,,NaN

In [18]:
df.to_csv('data/candidate-list-of-svhc-for-authorisation-export-cleaned.csv', index=False, quoting=csv.QUOTE_ALL)

In [ ]:
df.drop(columns=['Support document', 'Decision', 'Response to comments'], inplace=True)  # Drop the unnamed index column if it exists

KeyError: "['Support document', 'Decision', 'Response to comments'] not found in axis"

In [24]:
df.head(10)

,Substance name,Description,EC No.,CAS No.,Reason for inclusion,Date of inclusion,IUCLID dataset,Remarks
0,n-hexane,,203-777-6,110-54-3,Specific target organ toxicity after repeated ...,04-Feb-2026,,N-hexane is identified as a substance of very ...
1,"4,4'-[2,2,2-trifluoro-1-(trifluoromethyl)ethyl...",,-,-,Toxic for reproduction (Article 57c),04-Feb-2026,,
2,"Benzyltriphenylphosphonium, salt with 4,4'-[2,...",,278-305-5,75768-65-9,Toxic for reproduction (Article 57c),04-Feb-2026,,
3,"disodium 4,4'-[2,2,2-trifluoro-1-(trifluoromet...",,425-060-9,-,Toxic for reproduction (Article 57c),04-Feb-2026,,
4,"N,N-dibutyl-N-methylbutan-1-aminium 4-[1,1,1,3...",,443-330-4,-,Toxic for reproduction (Article 57c),04-Feb-2026,,
5,"Phosphonium, tributyl(2-methoxypropyl)-, salt ...",,468-740-0,126049-00-1,Toxic for reproduction (Article 57c),04-Feb-2026,,
6,"4,4'-[2,2,2-trifluoro-1-(trifluoromethyl)ethyl...",,216-036-7,1478-61-1,Toxic for reproduction (Article 57c),04-Feb-2026,,
7,"benzyl(diethylamino)diphenylphosphonium 4-[1,1...",,479-100-5,577705-90-9,Toxic for reproduction (Article 57c),04-Feb-2026,,
8,"Reaction mass of 4,4'-[2,2,2-trifluoro-1-(trif...",,-,-,Toxic for reproduction (Article 57c),04-Feb-2026,,
9,"Reaction mass of 4,4'-[2,2,2-trifluoro-1-(trif...",,-,-,Toxic for reproduction (Article 57c),04-Feb-2026,,

In [25]:
df.to_csv('data/candidate-list-of-svhc-for-authorisation-export-cleaned.csv', index=False, quoting=csv.QUOTE_ALL)

In [26]:
new_df = df[['Substance name', 'CAS No.']]

In [27]:
new_df.size

1028

In [28]:
new_df.to_csv('data/material_cas.csv', index=False, quoting=csv.QUOTE_ALL)

In [29]:
df = pd.read_csv('data/products_materials_all.csv')

In [31]:
df.head()

,product,CAS,materials
0,n-hexane,110-54-3,1-hexene
1,"4,4'-[2,2,2-trifluoro-1-(trifluoromethyl)ethyl...",-,Bisphenol A
2,"Benzyltriphenylphosphonium, salt with 4,4'-[2,...",75768-65-9,Benzyltriphenylphosphonium chloride
3,"disodium 4,4'-[2,2,2-trifluoro-1-(trifluoromet...",-,"4,4'-(hexafluoroisopropylidene)diphenol"
4,"N,N-dibutyl-N-methylbutan-1-aminium 4-[1,1,1,3...",-,"4,4'-(hexafluoroisopropylidene)diphenol"

In [32]:
new_df = df[['product', 'materials']]

In [33]:
new_df.to_csv('data/products_materials.csv')

In [40]:
df = pd.read_csv('data/products_materials.csv')
cas = pd.read_csv('data/product_cas.csv')

In [44]:
pd.concat([df, cas["CAS No."]], axis=1, ignore_index=True).to_csv('data/products_materials_cas.csv', index=False)

In [48]:
all_df = pd.read_csv('data/products_materials_cas.csv')

In [49]:
all_df.head(20)

,0,product,material,product cas
0,0.0,n-hexane,1-hexene,110-54-3
1,1.0,"4,4'-[2,2,2-trifluoro-1-(trifluoromethyl)ethyl...",Bisphenol A,-
2,2.0,"Benzyltriphenylphosphonium, salt with 4,4'-[2,...",Benzyltriphenylphosphonium chloride,75768-65-9
3,3.0,"disodium 4,4'-[2,2,2-trifluoro-1-(trifluoromet...","4,4'-(hexafluoroisopropylidene)diphenol",-
4,4.0,"N,N-dibutyl-N-methylbutan-1-aminium 4-[1,1,1,3...","4,4'-(hexafluoroisopropylidene)diphenol",-
5,5.0,"Phosphonium, tributyl(2-methoxypropyl)-, salt ...",Tributyl(2-methoxypropyl)phosphonium chloride,126049-00-1
6,6.0,"4,4'-[2,2,2-trifluoro-1-(trifluoromethyl)ethyl...","Hexafluoroacetone, Phenol",1478-61-1
7,7.0,"benzyl(diethylamino)diphenylphosphonium 4-[1,1...",benzyl(diethylamino)diphenylphosphonium chloride,577705-90-9
8,8.0,"Reaction mass of 4,4'-[2,2,2-trifluoro-1-(trif...","4,4'-(hexafluoroisopropylidene)diphenol",-
9,9.0,"Reaction mass of 4,4'-[2,2,2-trifluoro-1-(trif...","4,4'-(hexafluoroisopropylidene)diphenol",-
10,10.0,"Reaction products of benzene, chlorine and sul...",Unknown,921213-47-0
11,11.0,"1,1'-(ethane-1,2-diyl)bis[pentabromobenzene] (...",decabromodiphenyl ether,84852-53-9
12,12.0,tetra(sodium/potassium) 7-[(E)-{2-acetamido-4-...,Unknown,-
13,13.0,decamethyltetrasiloxane,dichlorodimethylsilane,141-62-8
14,14.0,"1,1,1,3,5,5,5-heptamethyl-3-[(trimethylsilyl)o...",Hexamethyldisiloxane,17928-28-8
15,15.0,reaction mass of: triphenylthiophosphate and t...,Phenol,192268-65-8
16,16.0,Perfluamine,Perfluorotributylamine,338-83-0
17,17.0,Octamethyltrisiloxane,Trimethylchlorosilane,107-51-7
18,18.0,"O,O,O-triphenyl phosphorothioate",Phenol,597-82-0
19,19.0,"6-[(C10-C13)-alkyl-(branched, unsaturated)-2,5...",6-aminohexanoic acid,2156592-54-8

In [3]:
from google import genai
import os
print("GEMINI_API_KEY" in os.environ)
print("GOOGLE_API_KEY" in os.environ)
client = genai.Client(api_key=os.environ["GEMINI_API_KEY"])  # Replace with
for model in client.models.list():
    print(model.name)

Both GOOGLE_API_KEY and GEMINI_API_KEY are set. Using GOOGLE_API_KEY.

True
True

ClientError: 403 PERMISSION_DENIED. {'error': {'code': 403, 'message': 'Your API key was reported as leaked. Please use another API key.', 'status': 'PERMISSION_DENIED'}}